// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOenk16h-Pf0IR_11Asn6iN8OE7ivw4ZM',
    appId: '1:234135585129:web:10f7ad9563d7be89a37df8',
    messagingSenderId: '234135585129',
    projectId: 'football-2b5b9',
    authDomain: 'football-2b5b9.firebaseapp.com',
    storageBucket: 'football-2b5b9.appspot.com',
    measurementId: 'G-BHF1MZJ9KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvxKmejEaDxWZ0CRfxzt88OS0DTbkkpsc',
    appId: '1:234135585129:android:96ca91f2c2480c41a37df8',
    messagingSenderId: '234135585129',
    projectId: 'football-2b5b9',
    storageBucket: 'football-2b5b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUln7KyxUcGpbYIx7vlTX3QnQvCU0n4qo',
    appId: '1:234135585129:ios:538ff61ffa83ca4ba37df8',
    messagingSenderId: '234135585129',
    projectId: 'football-2b5b9',
    storageBucket: 'football-2b5b9.appspot.com',
    iosBundleId: 'com.example.heshamm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUln7KyxUcGpbYIx7vlTX3QnQvCU0n4qo',
    appId: '1:234135585129:ios:538ff61ffa83ca4ba37df8',
    messagingSenderId: '234135585129',
    projectId: 'football-2b5b9',
    storageBucket: 'football-2b5b9.appspot.com',
    iosBundleId: 'com.example.heshamm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOenk16h-Pf0IR_11Asn6iN8OE7ivw4ZM',
    appId: '1:234135585129:web:0237e15ea6e69649a37df8',
    messagingSenderId: '234135585129',
    projectId: 'football-2b5b9',
    authDomain: 'football-2b5b9.firebaseapp.com',
    storageBucket: 'football-2b5b9.appspot.com',
    measurementId: 'G-KP1JPR0P0V',
  );
}
